stages:
  - setup
  - unit-test
  - build
  - release
  - deploy_staging
  - deploy_qa

variables:
  IMAGE: ebasley/cme
  NODE_VERSION: node:11.10-alpine
  CONTAINER_IMAGE: $IMAGE:$CI_COMMIT_SHORT_SHA
  LATEST_CONTAINER_IMAGE: $IMAGE:latest
  TAG_CONTAINER_IMAGE: $IMAGE:$CI_COMMIT_REF_NAME
  CI_REGISTRY: https://index.docker.io/v1/
  CI_REGISTRY_AUTH: ZWJhc2xleTpmcmVlcmlkZTE0

setup:
  stage: setup
  image: $NODE_VERSION
  script:
    - yarn
  artifacts:
    paths:
      - node_modules/
  tags:
    - kube
    - main

unit test:
  stage: unit-test
  image: $NODE_VERSION 
  script:
    - yarn test --coverage
  coverage: /All files\s*\|\s*([\d\.]+)/
  dependencies:
    - setup
  tags:
    - kube
    - main

build:
  stage: build
  image: $NODE_VERSION
  artifacts:
    paths:
      - build/
  script:
    - yarn build
  tags:
    - kube
    - main


build and push docker image:
  stage: release
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$CI_REGISTRY_AUTH\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CONTAINER_IMAGE --destination $LATEST_CONTAINER_IMAGE --destination $TAG_CONTAINER_IMAGE
  dependencies:
    - setup
    - build
  only:
    - develop
    - master
  tags:
    - kube
    - main

deploy staging:
  stage: deploy_staging
  image: google/cloud-sdk
  before_script:
    - echo ${KUBE_ACCOUNT_KEY} | base64 -di > key.json
  script:
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud config set project main-234215
    - gcloud config set container/cluster main
    - gcloud config set compute/region europe-west1-b
    - gcloud container clusters get-credentials main --region europe-west1-b
    - kubectl get pods -n staging -o wide
    - kubectl set image deployment/cme cme=$CONTAINER_IMAGE -n staging
    - kubectl set env deployment/cme GIT_HASH=$CI_COMMIT_SHA -n staging
  only:
    - develop
  environment:
    name: staging
  tags:
    - kube
    - main

deploy qa:
  stage: deploy_qa
  image: google/cloud-sdk
  before_script:
    - echo ${KUBE_ACCOUNT_KEY} | base64 -di > key.json
  script:
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud config set project main-234215
    - gcloud config set container/cluster main
    - gcloud config set compute/region europe-west1-b
    - gcloud container clusters get-credentials main --region europe-west1-b
    - kubectl get pods -n qa -o wide
    - kubectl set image deployment/cme cme=$CONTAINER_IMAGE -n qa
    - kubectl set env deployment/cme GIT_HASH=$CI_COMMIT_SHA -n qa
  only:
    - master
  environment:
    name: qa
  tags:
    - kube
    - main
