stages:
  - unit-test
  - build-image

image: node:latest

run unit test:
  stage: unit-test
  before_script:
    - yarn
  cache:
    untracked: true
    policy: pull
  script:
    - yarn test
  tags:
    - docker

build docker image:
  stage: build-image
  script:
    - docker info 
    - docker build -t redpelicans/cm .
  tags:
    - rp3

