stages:
  - unit-test

image: node:latest

run unit test:
  stage: unit-test
  before_script:
    - yarn
  cache:
    untracked: true
    policy: pull
  script:
    - yarn test
    - docker build -t redpelicans/cm .

