stages:
  - unit-test
  - build-image

image: node:latest

variables:
  CI_DEBUG_TRACE: "true"
  CONTAINER_TEST_IMAGE: redpelicans/cm:$CI_COMMIT_SHA
  CONTAINER_STAGING_IMAGE: redpelicans/cm:$CI_COMMIT_SHA
  CONTAINER_RELEASE_IMAGE: redpelicans/cm:latest

run unit test:
  stage: unit-test
  before_script:
    - yarn
  cache:
    untracked: true
    policy: pull
  script:
    - yarn test
  tags:
    - docker

build and push docker image:
  stage: build-image
  before_script:
    - docker login -u redpelicans -p $CI_JOB_TOKEN
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  only:
    - develop
  tags:
    - rp3

